[package]
name = "lmesh-wifi"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
dmesh-object-store = { path = "../dmesh-object-store" }
dmesh-rawnan = { path = "../rawnan" }
dmesh-transport = { path = "../dmesh-transport", features = ["udp"] }
libc = "0.2"
minicbor = "2.2"
sha2 = "0.11"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uart-codec = { path = "../uart-codec" }
mesh = { git = "https://github.com/costinm/ssh-mesh", package = "mesh" }
tokio = { version = "1", features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync"] }
tracing = "0.1"

[lib]
name = "lmesh_wifi"

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "lmesh-wifi"
path = "src/main.rs"
