[package]
name = "dmesh-server"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = { version = "0.11", default-features = false }
anyhow = { version = "1", optional = true }
hex = { version = "0.4", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
tokio = { version = "1", default-features = false, features = ["macros", "net", "rt", "rt-multi-thread", "io-util", "time", "sync", "fs"], optional = true }
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"], optional = true }

[features]
default = ["std", "udp"]
std = [
    "dep:anyhow",
    "dep:hex",
    "dep:serde",
    "dep:serde_json",
    "dep:tokio",
    "dep:tracing",
    "dep:tracing-subscriber",
]
udp = ["std", "dep:libc", "quic-lite/std"]

[dev-dependencies]
tempfile = "3"

[lib]
name = "dmesh_server"

[[example]]
name = "recovery-iperf-server"
required-features = ["udp"]
test = true

[[test]]
name = "running_lmesh_wifi"
required-features = ["udp"]

[dependencies.quic-lite]
path = "../quic-lite"
default-features = false

[dependencies.libc]
version = "0.2"
optional = true
