//! Standalone API artifact generator.
//!
//! This crate is a host build tool, never a runtime or firmware dependency.
//! API.md is the normative, Markdown-first API contract.

use std::collections::{BTreeMap, BTreeSet};

use anyhow::{Context, Result, anyhow, bail};
use serde_json::{Map, Value, json};

pub mod java;

const STANDARD_ERRORS: &[&str] = &[
    "unauthenticated",
    "permission_denied",
    "timeout",
    "remote_exception",
    "invalid_argument",
    "not_found",
    "conflict",
    "unavailable",
    "internal",
];

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ApiMethod {
    pub id: String,
    pub component: String,
    pub method: String,
    pub summary: String,
    pub visibility: String,
    pub component_index: Option<u32>,
    pub method_index: Option<u32>,
    pub ui_visibility: Option<String>,
    pub execution: Option<String>,
    pub recommended_timeout: Option<String>,
    pub access: Option<String>,
    /// Generate no-std Rust structs with fixed-buffer CBOR codecs.
    pub rust_cbor: bool,
    pub errors: Vec<ApiError>,
    pub request: ApiShape,
    pub response: ApiShape,
}

fn public_visibility() -> String {
    "public".to_owned()
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct ApiShape {
    pub fields: Vec<ApiField>,
    pub max_encoded_size: Option<String>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ApiField {
    pub name: String,
    pub index: u32,
    pub value_type: String,
    pub required: bool,
    pub default: Option<Value>,
    pub max: Option<String>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ApiError {
    pub name: String,
    pub description: String,
}

/// Render deterministic Rust request and response data types from API methods.
pub fn rust_api(methods: &[ApiMethod]) -> String {
    rust_api_with_tags(methods, false)
}

/// Render opt-in no-std Rust response structs with fixed-buffer CBOR codecs.
/// The schema must use required unsigned scalar fields so the generated codec
/// has no allocation or feature-dependent runtime.
pub fn rust_cbor_api(methods: &[ApiMethod]) -> String {
    let mut output = String::from("// Generated by mesh-api-gen from API.md; do not edit.\n\n");
    for method in methods.iter().filter(|method| method.rust_cbor) {
        assert!(
            method
                .response
                .fields
                .iter()
                .all(|field| field.required && field.value_type == "u64")
        );
        let name = format!(
            "{}{}Response",
            pascal_identifier(&method.component),
            pascal_identifier(&method.method)
        );
        output.push_str(&format!(
            "/// {}\n#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]\npub struct {name} {{\n",
            method.summary
        ));
        for field in &method.response.fields {
            output.push_str(&format!(
                "    /// API response field `{}`.\n    pub {}: u64,\n",
                field.name,
                rust_field_name(&field.name)
            ));
        }
        output.push_str("}\n\n");
        output.push_str(&format!("impl {name} {{\n    /// Encode this response as its numeric-tagged CBOR map.\n    pub fn encode_cbor(&self, out: &mut [u8]) -> Option<usize> {{\n        let mut encoder = crate::cbor::Encoder::new(out);\n        encoder.map({})?;\n", method.response.fields.len()));
        for field in &method.response.fields {
            output.push_str(&format!(
                "        encoder.uint({})?;\n        encoder.uint(self.{})?;\n",
                field.index,
                rust_field_name(&field.name)
            ));
        }
        output.push_str("        Some(encoder.len())\n    }\n\n    /// Decode a numeric-tagged CBOR map; reject unknown, duplicate, or missing tags.\n    pub fn decode_cbor(input: &[u8]) -> Option<Self> {\n        let mut decoder = crate::cbor::Decoder::new(input);\n        let (major, count) = decoder.head()?;\n        if major != 5 || count != ");
        output.push_str(&method.response.fields.len().to_string());
        output.push_str(" { return None; }\n        let mut values = [None; ");
        output.push_str(&method.response.fields.len().to_string());
        output.push_str("];\n        for _ in 0..count {\n            let tag = decoder.uint()?;\n            let index = match tag {\n");
        for (index, field) in method.response.fields.iter().enumerate() {
            output.push_str(&format!("                {} => {},\n", field.index, index));
        }
        output.push_str("                _ => return None,\n            };\n            if values[index].is_some() { return None; }\n            values[index] = Some(decoder.uint()?);\n        }\n        if !decoder.is_finished() { return None; }\n        Some(Self {\n");
        for (index, field) in method.response.fields.iter().enumerate() {
            output.push_str(&format!(
                "            {}: values[{}]?,\n",
                rust_field_name(&field.name),
                index
            ));
        }
        output.push_str("        })\n    }\n}\n\n");
    }
    while output.ends_with("\n\n") {
        output.pop();
    }
    output
}

/// Like [`rust_api`], and also implement `mesh::tagged::TaggedFields` for every
/// type, so the serde structs encode and decode the tag-keyed CBOR of `API.md`
/// directly. The consuming crate must depend on `mesh`.
pub fn rust_api_tagged(methods: &[ApiMethod]) -> String {
    rust_api_with_tags(methods, true)
}

fn rust_api_with_tags(methods: &[ApiMethod], tagged: bool) -> String {
    let mut output = String::from(
        "// Generated by mesh-api-gen from API.md; do not edit.\n\n\
use serde::{Deserialize, Serialize};\n\n",
    );
    for method in methods {
        render_rust_shape(&mut output, method, "request", tagged);
        render_rust_shape(&mut output, method, "response", tagged);
    }
    while output.ends_with("\n\n") {
        output.pop();
    }
    output
}

fn render_rust_shape(output: &mut String, method: &ApiMethod, shape: &str, tagged: bool) {
    let fields = if shape == "request" {
        &method.request.fields
    } else {
        &method.response.fields
    };
    let struct_name = format!(
        "{}{}{}",
        pascal_identifier(&method.component),
        pascal_identifier(&method.method),
        if shape == "request" {
            "Request"
        } else {
            "Response"
        }
    );
    output.push_str(&format!("/// {}\n", method.summary));
    output.push_str("#[derive(Clone, Debug, Deserialize, Serialize)]\n");
    if fields.is_empty() {
        output.push_str(&format!("pub struct {struct_name};\n\n"));
    } else {
        output.push_str(&format!("pub struct {struct_name} {{\n"));
        for field in fields {
            output.push_str(&format!("    /// API field `{}`.\n", field.name));
            if !field.required {
                output
                    .push_str("    #[serde(default, skip_serializing_if = \"Option::is_none\")]\n");
            }
            output.push_str(&format!(
                "    pub {}: {},\n",
                rust_field_name(&field.name),
                rust_value_type(&field.value_type, field.required)
            ));
        }
        output.push_str("}\n\n");
    }
    if tagged {
        output.push_str(&format!(
            "impl mesh::tagged::TaggedFields for {struct_name} {{\n    const FIELDS: &'static [(&'static str, u32)] = &["
        ));
        let entries: Vec<String> = fields
            .iter()
            .map(|field| format!("(\"{}\", {})", field.name, field.index))
            .collect();
        output.push_str(&entries.join(", "));
        output.push_str("];\n}\n\n");
    }
}

fn pascal_identifier(value: &str) -> String {
    value
        .split(|character: char| !character.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => format!("{}{}", first.to_ascii_uppercase(), chars.as_str()),
                None => String::new(),
            }
        })
        .collect()
}

fn rust_field_name(value: &str) -> String {
    match value {
        "type" | "match" | "ref" | "self" | "super" | "crate" => format!("r#{value}"),
        _ => value.to_owned(),
    }
}

fn rust_value_type(value_type: &str, required: bool) -> String {
    if let Some(item) = value_type.strip_suffix("[]") {
        let item = rust_value_type(item, true);
        return if required {
            format!("Vec<{item}>")
        } else {
            format!("Option<Vec<{item}>>")
        };
    }
    let value = match value_type {
        "bool" => "bool",
        "u8" => "u8",
        "u16" => "u16",
        "u32" => "u32",
        "u64" => "u64",
        "i8" => "i8",
        "i16" => "i16",
        "i32" => "i32",
        "i64" => "i64",
        "f32" => "f32",
        "f64" => "f64",
        "string" => "String",
        "bytes" => "Vec<u8>",
        "array" => "Vec<serde_json::Value>",
        "object" => "serde_json::Value",
        value if value.starts_with("map<") => {
            "std::collections::BTreeMap<String, serde_json::Value>"
        }
        _ => "serde_json::Value",
    };
    if required {
        value.to_owned()
    } else {
        format!("Option<{value}>")
    }
}

/// Parse a Markdown-first API document.
pub fn parse_api_markdown(markdown: &str) -> Result<Vec<ApiMethod>> {
    let lines: Vec<_> = markdown.lines().collect();
    let mut methods = Vec::new();
    let mut component: Option<(String, Option<u32>)> = None;
    let mut in_types = false;
    let mut current: Option<ApiMethod> = None;
    let mut shape: Option<&str> = None;
    let mut named_shapes: BTreeMap<String, ApiShape> = BTreeMap::new();
    let mut named_shape: Option<String> = None;
    let mut references: Vec<(usize, bool, String)> = Vec::new();
    let mut index = 0;

    while index < lines.len() {
        let line = lines[index].trim();
        if let Some((name, component_index)) = component_heading(line)? {
            finish_method(&mut methods, &mut current);
            component = Some((name, component_index));
            in_types = false;
            shape = None;
            named_shape = None;
            index += 1;
            continue;
        }
        if line == "# Types" {
            finish_method(&mut methods, &mut current);
            component = None;
            in_types = true;
            shape = None;
            named_shape = None;
            index += 1;
            continue;
        }
        if in_types && line.starts_with("## enum ") {
            finish_method(&mut methods, &mut current);
            named_shape = None;
            shape = None;
            index += 1;
            continue;
        }
        if in_types && let Some(name) = type_heading(line) {
            finish_method(&mut methods, &mut current);
            named_shapes.insert(name.clone(), ApiShape::default());
            named_shape = Some(name);
            shape = None;
            index += 1;
            continue;
        }
        if let Some((method, method_index, summary)) = method_heading(line)? {
            let (component_name, component_index) = component
                .clone()
                .ok_or_else(|| anyhow!("method heading outside a component: {line}"))?;
            finish_method(&mut methods, &mut current);
            current = Some(ApiMethod {
                id: format!("{component_name}.{method}"),
                component: component_name,
                method,
                summary,
                visibility: public_visibility(),
                component_index,
                method_index,
                ui_visibility: None,
                execution: None,
                recommended_timeout: None,
                access: None,
                rust_cbor: false,
                errors: Vec::new(),
                request: ApiShape::default(),
                response: ApiShape::default(),
            });
            shape = None;
            named_shape = None;
            index += 1;
            continue;
        }
        if let Some(current) = current.as_mut() {
            if let Some((key, value)) = metadata(line) {
                match key {
                    "Visibility" => current.visibility = value.to_owned(),
                    "UI" => current.ui_visibility = Some(value.to_owned()),
                    "Execution" => current.execution = Some(value.to_owned()),
                    "Recommended timeout" => current.recommended_timeout = Some(unquote(value)),
                    "Access" => current.access = Some(value.to_owned()),
                    "Rust CBOR" => current.rust_cbor = value == "generated",
                    "Max encoded size" => match shape {
                        Some("request") => current.request.max_encoded_size = Some(unquote(value)),
                        Some("response") => {
                            current.response.max_encoded_size = Some(unquote(value))
                        }
                        _ => bail!("Max encoded size must occur in a request or response"),
                    },
                    "Request" | "Response" => {
                        let name = type_name(value)
                            .ok_or_else(|| anyhow!("{key} must reference a named type"))?;
                        references.push((methods.len(), key == "Response", name));
                    }
                    _ => {}
                }
            }
            if line == "### Request" {
                shape = Some("request");
            } else if line == "### Response" {
                shape = Some("response");
            } else if line == "### Errors" {
                let (errors, next) = parse_error_table(&lines, index + 1)?;
                current.errors = errors;
                index = next;
                continue;
            } else if shape.is_some() && line.starts_with('|') {
                if !table_cells(line).iter().any(|header| header == "Tag") {
                    index += 1;
                    continue;
                }
                let (fields, next) = parse_field_table(&lines, index)?;
                match shape {
                    Some("request") => current.request.fields = fields,
                    Some("response") => current.response.fields = fields,
                    _ => bail!("field table outside request or response"),
                }
                shape = None;
                index = next;
                continue;
            }
        } else if let Some(name) = named_shape.clone() {
            if let Some(size) = metadata(line)
                .filter(|(key, _)| *key == "Max encoded size")
                .map(|(_, value)| unquote(value))
            {
                named_shapes
                    .get_mut(&name)
                    .expect("named shape exists")
                    .max_encoded_size = Some(size);
            } else if line.starts_with('|') {
                let (fields, next) = parse_field_table(&lines, index)?;
                named_shapes
                    .get_mut(&name)
                    .expect("named shape exists")
                    .fields = fields;
                index = next;
                continue;
            }
        }
        index += 1;
    }
    finish_method(&mut methods, &mut current);
    for (method_index, response, name) in references {
        let named = named_shapes
            .get(&name)
            .ok_or_else(|| anyhow!("unknown named type {name}"))?
            .clone();
        let method = methods
            .get_mut(method_index)
            .ok_or_else(|| anyhow!("internal method reference error"))?;
        if response {
            method.response = named;
        } else {
            method.request = named;
        }
    }
    validate(&methods)?;
    Ok(methods)
}

fn finish_method(methods: &mut Vec<ApiMethod>, current: &mut Option<ApiMethod>) {
    if let Some(method) = current.take() {
        methods.push(method);
    }
}

fn component_heading(line: &str) -> Result<Option<(String, Option<u32>)>> {
    let Some(value) = line.strip_prefix("# ") else {
        return Ok(None);
    };
    let Some((name, suffix)) = value.split_once("` API") else {
        return Ok(None);
    };
    let name = name.trim().trim_matches('`').to_owned();
    if name.is_empty() {
        bail!("component name is empty")
    }
    let index = parse_optional_index(suffix)?;
    Ok(Some((name, index)))
}

fn method_heading(line: &str) -> Result<Option<(String, Option<u32>, String)>> {
    let Some(value) = line.strip_prefix("## ") else {
        return Ok(None);
    };
    if value.starts_with("enum ") {
        return Ok(None);
    }
    let (before, summary) = value.split_once(" — ").unwrap_or((value, ""));
    let (method_index, name) = if let Some((index, rest)) = before.split_once(". `") {
        (
            Some(index.trim().parse().context("parse method index")?),
            rest.trim_end_matches('`'),
        )
    } else if before.trim().starts_with('`') {
        (None, before.trim().trim_matches('`'))
    } else {
        return Ok(None);
    };
    if name.is_empty() {
        bail!("method name is empty")
    }
    Ok(Some((name.to_owned(), method_index, summary.to_owned())))
}

fn type_heading(line: &str) -> Option<String> {
    let value = line.strip_prefix("## ")?;
    if value.starts_with("enum ") {
        return None;
    }
    if value.contains(" — ") || value.contains(". `") {
        return None;
    }
    let name = value.trim().trim_matches('`');
    (!name.is_empty()).then(|| name.to_owned())
}

fn parse_optional_index(value: &str) -> Result<Option<u32>> {
    let value = value.trim();
    if value.is_empty() {
        return Ok(None);
    }
    let value = value
        .strip_prefix('(')
        .and_then(|value| value.strip_suffix(')'))
        .ok_or_else(|| anyhow!("component index must be written as (N)"))?;
    Ok(Some(value.parse().context("parse component index")?))
}

fn metadata(line: &str) -> Option<(&str, &str)> {
    let value = line.strip_prefix("**")?;
    let (key, value) = value.split_once(":**")?;
    Some((key, value.trim()))
}

fn unquote(value: &str) -> String {
    value.trim().trim_matches('`').to_owned()
}

fn type_name(value: &str) -> Option<String> {
    let value = value.trim();
    let value = value.strip_prefix('[')?.split_once(']')?.0;
    Some(value.trim_matches('`').to_owned())
}

fn parse_field_table(lines: &[&str], start: usize) -> Result<(Vec<ApiField>, usize)> {
    let headers = table_cells(lines.get(start).copied().unwrap_or_default());
    if !headers.iter().any(|header| header == "Tag") {
        bail!(
            "field table needs a Tag column: {}",
            lines.get(start).copied().unwrap_or_default()
        )
    }
    let mut fields = Vec::new();
    let mut index = start + 2;
    while index < lines.len() && lines[index].trim_start().starts_with('|') {
        let cells = table_cells(lines[index]);
        let get = |name: &str| {
            headers
                .iter()
                .position(|header| header == name)
                .and_then(|column| cells.get(column))
                .map(String::as_str)
                .unwrap_or("")
        };
        let tag = get("Tag")
            .parse()
            .with_context(|| format!("parse tag in {}", lines[index]))?;
        let default = get("Default");
        let required = match get("Required") {
            "" | "no" | "false" => false,
            "yes" | "true" => true,
            value => bail!("invalid Required value `{value}` in {}", lines[index]),
        };
        fields.push(ApiField {
            name: unquote(get("Field")),
            index: tag,
            value_type: type_name_cell(get("Type")),
            required,
            default: (!default.is_empty())
                .then(|| parse_default(default))
                .transpose()?,
            max: (!get("Max").is_empty()).then(|| unquote(get("Max"))),
        });
        index += 1;
    }
    Ok((fields, index))
}

fn parse_error_table(lines: &[&str], start: usize) -> Result<(Vec<ApiError>, usize)> {
    let mut start = start;
    while start < lines.len() && lines[start].trim().is_empty() {
        start += 1;
    }
    let headers = table_cells(lines.get(start).copied().unwrap_or_default());
    if !headers.iter().any(|header| header == "Error") {
        bail!("error table needs an Error column")
    }
    let mut errors = Vec::new();
    let mut index = start + 2;
    while index < lines.len() && lines[index].trim_start().starts_with('|') {
        let cells = table_cells(lines[index]);
        let get = |name: &str| {
            headers
                .iter()
                .position(|header| header == name)
                .and_then(|column| cells.get(column))
                .map(String::as_str)
                .unwrap_or("")
        };
        errors.push(ApiError {
            name: unquote(get("Error")),
            description: get("Meaning").to_owned(),
        });
        index += 1;
    }
    Ok((errors, index))
}

fn table_cells(line: &str) -> Vec<String> {
    line.trim()
        .trim_matches('|')
        .split('|')
        .map(|cell| cell.trim().to_owned())
        .collect()
}

fn type_name_cell(value: &str) -> String {
    let value = value.trim();
    if let Some(label) = value
        .strip_prefix('[')
        .and_then(|value| value.split_once("](").map(|(label, _)| label))
    {
        return label.trim_matches('`').to_owned();
    }
    value.trim_matches('`').to_owned()
}

fn parse_default(value: &str) -> Result<Value> {
    let value = unquote(value);
    if let Ok(value) = serde_json::from_str(&value) {
        return Ok(value);
    }
    Ok(Value::String(value))
}

/// Bootstrap a Markdown API draft from a catalog. The draft deliberately does
/// not assign numeric IDs or field tags; a maintainer must review them.
pub fn api_markdown_from_tools_json(value: &Value) -> Result<String> {
    api_markdown_from_tools_json_for_component(value, None)
}

/// Like [`api_markdown_from_tools_json`] but supplies a component for catalogs
/// whose method names are bare verbs such as `status` or `start`.
pub fn api_markdown_from_tools_json_for_component(
    value: &Value,
    default_component: Option<&str>,
) -> Result<String> {
    let tools = value
        .as_array()
        .or_else(|| value.get("tools").and_then(Value::as_array))
        .ok_or_else(|| anyhow!("tools catalog must be an array or object with tools"))?;
    let mut output = String::new();
    for tool in tools {
        let name = tool
            .get("name")
            .and_then(Value::as_str)
            .ok_or_else(|| anyhow!("tools catalog entry lacks name"))?;
        let (component, method) = name
            .split_once('.')
            .unwrap_or((default_component.unwrap_or(""), name));
        output.push_str(&format!("# `{component}` API\n\n## `{method}`"));
        if let Some(summary) = tool.get("description").and_then(Value::as_str) {
            output.push_str(&format!(" — {summary}"));
        }
        output.push_str("\n\n");
        if let Some(properties) = tool
            .pointer("/inputSchema/properties")
            .and_then(Value::as_object)
        {
            output.push_str(
                "### Request\n\n| Tag | Field | Type | Description |\n|---:|---|---|---|\n",
            );
            for (field, property) in properties {
                output.push_str(&format!(
                    "| ? | `{field}` | `{}` | Assign a stable tag during review. |\n",
                    schema_type(property).unwrap_or("object")
                ));
            }
        }
        output.push('\n');
    }
    Ok(output)
}

fn schema_type(value: &Value) -> Option<&str> {
    let value = value.get("type")?;
    match value {
        Value::String(value) => Some(schema_primitive(value)),
        Value::Array(values) => values
            .iter()
            .filter_map(Value::as_str)
            .map(schema_primitive)
            .next(),
        _ => None,
    }
}

fn schema_primitive(value: &str) -> &'static str {
    match value {
        "boolean" => "bool",
        "integer" => "i64",
        "number" => "f64",
        "string" => "string",
        "array" => "array",
        "object" => "object",
        _ => "object",
    }
}

pub fn tools_json(methods: &[ApiMethod]) -> Value {
    Value::Array(
        methods
            .iter()
            .filter(|method| method.visibility == "public")
            .map(|method| {
                let mut tool = Map::new();
                tool.insert(
                    "name".to_owned(),
                    Value::String(format!("{}.{}", method.component, method.method)),
                );
                tool.insert(
                    "description".to_owned(),
                    Value::String(method.summary.clone()),
                );
                if let Some(index) = method.component_index {
                    tool.insert("x-component-index".to_owned(), Value::from(index));
                }
                if let Some(index) = method.method_index {
                    tool.insert("x-method-index".to_owned(), Value::from(index));
                }
                if let Some(visibility) = &method.ui_visibility {
                    tool.insert(
                        "x-ui-visibility".to_owned(),
                        Value::String(visibility.clone()),
                    );
                }
                if let Some(execution) = &method.execution {
                    tool.insert("x-execution".to_owned(), Value::String(execution.clone()));
                }
                if let Some(timeout) = &method.recommended_timeout {
                    tool.insert(
                        "x-recommended-timeout".to_owned(),
                        Value::String(timeout.clone()),
                    );
                }
                if let Some(access) = &method.access {
                    tool.insert("x-access".to_owned(), Value::String(access.clone()));
                }
                tool.insert(
                    "x-standard-errors".to_owned(),
                    Value::Array(
                        STANDARD_ERRORS
                            .iter()
                            .map(|error| Value::String((*error).to_owned()))
                            .collect(),
                    ),
                );
                if !method.errors.is_empty() {
                    tool.insert(
                        "x-errors".to_owned(),
                        Value::Array(method.errors.iter().map(|error| {
                            json!({"name": error.name, "description": error.description})
                        }).collect()),
                    );
                }
                tool.insert("inputSchema".to_owned(), shape_schema(&method.request));
                tool.insert("outputSchema".to_owned(), shape_schema(&method.response));
                Value::Object(tool)
            })
            .collect(),
    )
}

/// Overlay reviewed generated entries onto a legacy tools catalog.
///
/// This enables incremental migration: a service may publish stable numeric
/// tags for a reviewed subset while retaining older tools as visible,
/// schema-less JSON-RPC operations. Generated entries replace a legacy entry
/// with the same fully-qualified `name`; they do not invent IDs for the rest.
pub fn merge_tools_json(base: &Value, methods: &[ApiMethod]) -> Result<Value> {
    let base = base
        .as_array()
        .or_else(|| base.get("tools").and_then(Value::as_array))
        .context("base tools catalog must be an array or object with tools")?;
    let generated = tools_json(methods);
    let generated = generated
        .as_array()
        .expect("tools_json always returns an array");
    let replacements: BTreeMap<_, _> = generated
        .iter()
        .filter_map(|tool| {
            tool.get("name")
                .and_then(Value::as_str)
                .map(|name| (name, tool))
        })
        .collect();
    let mut merged = Vec::with_capacity(base.len() + generated.len());
    let mut replaced = BTreeSet::new();
    for tool in base {
        let Some(name) = tool.get("name").and_then(Value::as_str) else {
            bail!("base tools catalog entry has no string name");
        };
        let replacement = replacements.get(name).copied().or_else(|| {
            // Legacy catalogs commonly spell a service method as `status`
            // or `raw.check`, while the tagged API uses `lmesh.status` or
            // `wifi.raw.check`. Overlay it only when exactly one reviewed
            // entry has that suffix; ambiguity leaves the legacy entry alone.
            let suffix = format!(".{name}");
            let matches: Vec<_> = generated
                .iter()
                .filter(|tool| {
                    tool["name"]
                        .as_str()
                        .is_some_and(|candidate| candidate.ends_with(&suffix))
                })
                .collect();
            (matches.len() == 1).then(|| matches[0])
        });
        if let Some(replacement) = replacement {
            merged.push((*replacement).clone());
            replaced.insert(
                replacement["name"]
                    .as_str()
                    .expect("generated tool always has a name"),
            );
        } else {
            merged.push(tool.clone());
        }
    }
    for tool in generated {
        let name = tool["name"]
            .as_str()
            .expect("generated tool always has a name");
        if !replaced.contains(name) {
            merged.push(tool.clone());
        }
    }
    Ok(Value::Array(merged))
}

/// Produce a standard JSON Schema for text/JSON gateways. The numeric wire
/// identities remain explicit `x-*` metadata rather than a JSON Schema or
/// protobuf claim.
pub fn json_schema(methods: &[ApiMethod]) -> Value {
    let variants: Vec<_> = methods
        .iter()
        .filter(|method| method.visibility == "public")
        .map(|method| {
            let mut schema = shape_schema(&method.request);
            let object = schema
                .as_object_mut()
                .expect("shape_schema always creates an object");
            let properties = object
                .get_mut("properties")
                .and_then(Value::as_object_mut)
                .expect("shape_schema always creates properties");
            properties.insert(
                "method".to_owned(),
                json!({"const": format!("{}.{}", method.component, method.method)}),
            );
            let required = object
                .get_mut("required")
                .and_then(Value::as_array_mut)
                .expect("shape_schema always creates required");
            required.insert(0, Value::String("method".to_owned()));
            if let Some(index) = method.component_index {
                object.insert("x-component-index".to_owned(), Value::from(index));
            }
            if let Some(index) = method.method_index {
                object.insert("x-method-index".to_owned(), Value::from(index));
            }
            schema
        })
        .collect();
    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "oneOf": variants,
    })
}

fn shape_schema(shape: &ApiShape) -> Value {
    let mut properties = Map::new();
    let mut required = Vec::new();
    for field in &shape.fields {
        let mut property = Map::new();
        property.insert(
            "type".to_owned(),
            Value::String(json_type(&field.value_type).to_owned()),
        );
        property.insert("x-protobuf-index".to_owned(), Value::from(field.index));
        property.insert(
            "x-protobuf-type".to_owned(),
            Value::String(field.value_type.clone()),
        );
        if let Some(default) = &field.default {
            property.insert("default".to_owned(), default.clone());
        }
        if let Some(max) = &field.max {
            property.insert("x-max".to_owned(), Value::String(max.clone()));
        }
        if field.required {
            required.push(Value::String(field.name.clone()));
        }
        properties.insert(field.name.clone(), Value::Object(property));
    }
    let mut schema = json!({"type": "object", "properties": properties, "required": required});
    if let Some(max) = &shape.max_encoded_size {
        schema["x-max-encoded-size"] = Value::String(max.clone());
    }
    schema
}

fn json_type(value_type: &str) -> &'static str {
    if value_type.ends_with("[]") {
        return "array";
    }
    if value_type.starts_with("map<") {
        return "object";
    }
    match value_type {
        "bool" => "boolean",
        "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" => "integer",
        "f32" | "f64" => "number",
        "bytes" => "string",
        "array" => "array",
        "object" => "object",
        _ => "string",
    }
}

pub fn rust_ids(methods: &[ApiMethod]) -> String {
    let mut output = String::from("// Generated by mesh-api-gen; do not edit.\n\n");
    let mut emitted_components = BTreeSet::new();
    for method in methods {
        let component = identifier(&method.component);
        let name = identifier(&format!("{}_{}", method.component, method.method));
        if let Some(index) = method.component_index
            && emitted_components.insert(component.clone())
        {
            output.push_str(&format!(
                "pub const COMPONENT_{component}: u32 = {index};\n"
            ));
        }
        if let Some(index) = method.method_index {
            output.push_str(&format!("pub const METHOD_{name}: u32 = {index};\n"));
        }
        for field in &method.request.fields {
            output.push_str(&format!(
                "pub const FIELD_{}_{}: u32 = {};\n",
                name,
                identifier(&field.name),
                field.index
            ));
        }
    }
    output
}

fn identifier(value: &str) -> String {
    value
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

fn validate(methods: &[ApiMethod]) -> Result<()> {
    let mut ids = BTreeSet::new();
    let mut wire_methods = BTreeSet::new();
    let mut components = BTreeMap::new();
    for method in methods {
        if !ids.insert(&method.id) {
            bail!("duplicate API id {}", method.id);
        }
        if method.component.is_empty() || method.method.is_empty() {
            bail!("{} has an empty component or method", method.id);
        }
        if !matches!(method.visibility.as_str(), "public" | "private") {
            bail!("{} has invalid visibility {}", method.id, method.visibility);
        }
        if let Some(component_index) = method.component_index
            && let Some(previous) = components.insert(component_index, &method.component)
            && previous != &method.component
        {
            bail!(
                "component index {component_index} is used by both {previous} and {}",
                method.component
            );
        }
        if let (Some(component), Some(method_index)) = (method.component_index, method.method_index)
            && !wire_methods.insert((component, method_index))
        {
            bail!("duplicate component/method index {component}/{method_index}");
        }
        validate_fields(&method.id, &method.request.fields)?;
        validate_fields(&method.id, &method.response.fields)?;
    }
    Ok(())
}

fn validate_fields(id: &str, fields: &[ApiField]) -> Result<()> {
    let mut indices = BTreeSet::new();
    for field in fields {
        if field.index == 0 || !indices.insert(field.index) {
            bail!("{id} has duplicate or zero field index {}", field.index);
        }
        if field.value_type.is_empty() {
            bail!("{id}.{} has an empty type", field.name);
        }
    }
    Ok(())
}

pub fn parse_required_path(value: Option<String>, name: &str) -> Result<String> {
    value.ok_or_else(|| anyhow!("{name} is required"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_the_complete_markdown_fixture() {
        let methods = parse_api_markdown(include_str!("../API.md")).unwrap();
        assert_eq!(methods.len(), 7);
        assert_eq!(methods[0].id, "full.initialize");
        assert_eq!(methods[2].execution.as_deref(), Some("blocking"));
        assert_eq!(methods[2].recommended_timeout.as_deref(), Some("8s"));
        assert_eq!(methods[2].errors[1].name, "conflict");
        assert_eq!(
            methods[1].request.max_encoded_size.as_deref(),
            Some("1000 B")
        );
        assert_eq!(methods[1].request.fields[0].max.as_deref(), Some("960 B"));
        assert_eq!(methods[3].response.fields[0].value_type, "Entry[]");
        assert_eq!(methods[5].component, "host.diagnostics");
        assert!(
            tools_json(&methods)
                .as_array()
                .unwrap()
                .iter()
                .all(|tool| tool["name"] != "full.reset")
        );
    }

    #[test]
    fn generated_catalog_preserves_method_metadata() {
        let methods = parse_api_markdown(include_str!("../API.md")).unwrap();
        let tools = tools_json(&methods);
        let configure = tools
            .as_array()
            .unwrap()
            .iter()
            .find(|tool| tool["name"] == "full.configure")
            .unwrap();
        assert_eq!(configure["x-execution"], "blocking");
        assert_eq!(configure["x-recommended-timeout"], "8s");
        assert_eq!(configure["x-standard-errors"][0], "unauthenticated");
        assert_eq!(configure["x-errors"][1]["name"], "conflict");
        let list = tools
            .as_array()
            .unwrap()
            .iter()
            .find(|tool| tool["name"] == "full.list")
            .unwrap();
        assert_eq!(
            list["outputSchema"]["properties"]["entries"]["type"],
            "array"
        );
    }

    #[test]
    fn rejects_duplicate_field_tags() {
        let error = parse_api_markdown(
            "# `service` API (1)\n\n## 1. `set` — Set state\n\n### Request\n\n| Tag | Field | Type | Description |\n|---:|---|---|---|\n| 1 | `first` | `u8` | First. |\n| 1 | `second` | `u8` | Second. |\n",
        )
        .unwrap_err();
        assert!(error.to_string().contains("duplicate or zero field index"));
    }

    #[test]
    fn generates_fixed_buffer_cbor_for_required_numeric_response() {
        let methods = parse_api_markdown(
            "# `telemetry` API (7)\n\n## 7. `quic_metrics` — Read QUIC counters\n\n**Platforms:** E\n\n**Rust CBOR:** generated\n\n### Response\n\n| Tag | Field | Type | Required | Description |\n|---:|---|---|---|---|\n| 1 | `received_packets` | `u64` | yes | Packets. |\n",
        )
        .unwrap();
        assert!(methods[0].response.fields[0].required);
        let generated = rust_cbor_api(&methods);
        assert!(generated.contains("pub struct TelemetryQuicMetricsResponse"));
        assert!(generated.contains("crate::cbor::Encoder::new(out)"));
        assert!(generated.contains("crate::cbor::Decoder::new(input)"));
        assert!(generated.contains("received_packets: values[0]?"));
    }
}
