[workspace]
members = [
    "crates/dmesh",
    "crates/dmesh-store",
    "crates/dmesh-object-store",
    "crates/dmesh-transport",
    "crates/dmeshtui",
    "crates/dmeshui",
    "crates/lmesh",
    "crates/rawnan",
    "crates/tun",
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.0"
publish = false
