// Generated by mesh-api-gen from API.md; do not edit.

use serde::{Deserialize, Serialize};

/// Return owned open-AP status
/// mesh-api: summary = "Return owned open-AP status"
/// mesh-api: id = "wifi.ap.status"
/// mesh-api: component = "wifi"
/// mesh-api: method = "ap.status"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 1
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiApStatusRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
}

/// Return owned open-AP status
/// mesh-api: summary = "Return owned open-AP status"
/// mesh-api: id = "wifi.ap.status"
/// mesh-api: component = "wifi"
/// mesh-api: method = "ap.status"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 1
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiApStatusResponse;

/// Return owned station status
/// mesh-api: summary = "Return owned station status"
/// mesh-api: id = "wifi.sta.status"
/// mesh-api: component = "wifi"
/// mesh-api: method = "sta.status"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 2
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiStaStatusRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
}

/// Return owned station status
/// mesh-api: summary = "Return owned station status"
/// mesh-api: id = "wifi.sta.status"
/// mesh-api: component = "wifi"
/// mesh-api: method = "sta.status"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 2
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiStaStatusResponse;

/// Return raw-NAN status, the bounded one-hour cross-bearer discovered-device inventory, and NAN follow-ups. New/dropped devices append JSONL records to LMESH_DISCOVERY_LOG or LMESH_WIFI_DISCOVERY_LOG (default /run/mesh/lmesh-wifi/discovery.jsonl); routine refreshes do not log.
/// mesh-api: summary = "Return raw-NAN status, the bounded one-hour cross-bearer discovered-device inventory, and NAN follow-ups. New/dropped devices append JSONL records to LMESH_DISCOVERY_LOG or LMESH_WIFI_DISCOVERY_LOG (default /run/mesh/lmesh-wifi/discovery.jsonl); routine refreshes do not log."
/// mesh-api: id = "wifi.rawnan.status"
/// mesh-api: component = "wifi"
/// mesh-api: method = "rawnan.status"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 3
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawnanStatusRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
}

/// Return raw-NAN status, the bounded one-hour cross-bearer discovered-device inventory, and NAN follow-ups. New/dropped devices append JSONL records to LMESH_DISCOVERY_LOG or LMESH_WIFI_DISCOVERY_LOG (default /run/mesh/lmesh-wifi/discovery.jsonl); routine refreshes do not log.
/// mesh-api: summary = "Return raw-NAN status, the bounded one-hour cross-bearer discovered-device inventory, and NAN follow-ups. New/dropped devices append JSONL records to LMESH_DISCOVERY_LOG or LMESH_WIFI_DISCOVERY_LOG (default /run/mesh/lmesh-wifi/discovery.jsonl); routine refreshes do not log."
/// mesh-api: id = "wifi.rawnan.status"
/// mesh-api: component = "wifi"
/// mesh-api: method = "rawnan.status"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 3
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawnanStatusResponse;

/// Replace the local active NAN Publish Service Info. An enabled descriptor is emitted once in the next confirmed discovery window and then at the bounded refresh cadence; this request never transmits immediately or changes interface state. service_info_hex is the bounded CBOR Service Info payload.
/// mesh-api: summary = "Replace the local active NAN Publish Service Info. An enabled descriptor is emitted once in the next confirmed discovery window and then at the bounded refresh cadence; this request never transmits immediately or changes interface state. service_info_hex is the bounded CBOR Service Info payload."
/// mesh-api: id = "wifi.rawnan.active_publish"
/// mesh-api: component = "wifi"
/// mesh-api: method = "rawnan.active_publish"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 15
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawnanActivePublishRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
    /// API field `enabled`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// API field `service_info_hex`.
    /// mesh-api-field: index = 3
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_info_hex: Option<String>,
}

/// Replace the local active NAN Publish Service Info. An enabled descriptor is emitted once in the next confirmed discovery window and then at the bounded refresh cadence; this request never transmits immediately or changes interface state. service_info_hex is the bounded CBOR Service Info payload.
/// mesh-api: summary = "Replace the local active NAN Publish Service Info. An enabled descriptor is emitted once in the next confirmed discovery window and then at the bounded refresh cadence; this request never transmits immediately or changes interface state. service_info_hex is the bounded CBOR Service Info payload."
/// mesh-api: id = "wifi.rawnan.active_publish"
/// mesh-api: component = "wifi"
/// mesh-api: method = "rawnan.active_publish"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 15
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawnanActivePublishResponse;

/// Resolve a discovery-selected comprehensive pair probe and return the live ESP/Android/Host fleet without changing the control-plane radio
/// mesh-api: summary = "Resolve a discovery-selected comprehensive pair probe and return the live ESP/Android/Host fleet without changing the control-plane radio"
/// mesh-api: id = "wifi.probe.plan"
/// mesh-api: component = "wifi"
/// mesh-api: method = "probe.plan"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 16
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiProbePlanRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
    /// API field `source_id`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = true
    pub source_id: String,
    /// API field `target_id`.
    /// mesh-api-field: index = 3
    /// mesh-api-field: required = true
    pub target_id: String,
    /// API field `short_bytes`.
    /// mesh-api-field: index = 4
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub short_bytes: Option<u32>,
    /// API field `long_bytes`.
    /// mesh-api-field: index = 5
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub long_bytes: Option<u32>,
}

/// Resolve a discovery-selected comprehensive pair probe and return the live ESP/Android/Host fleet without changing the control-plane radio
/// mesh-api: summary = "Resolve a discovery-selected comprehensive pair probe and return the live ESP/Android/Host fleet without changing the control-plane radio"
/// mesh-api: id = "wifi.probe.plan"
/// mesh-api: component = "wifi"
/// mesh-api: method = "probe.plan"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 16
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiProbePlanResponse;

/// Return owned interface status
/// mesh-api: summary = "Return owned interface status"
/// mesh-api: id = "wifi.interface.status"
/// mesh-api: component = "wifi"
/// mesh-api: method = "interface.status"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 4
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiInterfaceStatusRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
}

/// Return owned interface status
/// mesh-api: summary = "Return owned interface status"
/// mesh-api: id = "wifi.interface.status"
/// mesh-api: component = "wifi"
/// mesh-api: method = "interface.status"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 4
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiInterfaceStatusResponse;

/// Return associated station metrics for an AP interface
/// mesh-api: summary = "Return associated station metrics for an AP interface"
/// mesh-api: id = "wifi.ap.stations"
/// mesh-api: component = "wifi"
/// mesh-api: method = "ap.stations"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 5
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiApStationsRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
}

/// Return associated station metrics for an AP interface
/// mesh-api: summary = "Return associated station metrics for an AP interface"
/// mesh-api: id = "wifi.ap.stations"
/// mesh-api: component = "wifi"
/// mesh-api: method = "ap.stations"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 5
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiApStationsResponse;

/// Return bounded raw action receive and dispatch counters
/// mesh-api: summary = "Return bounded raw action receive and dispatch counters"
/// mesh-api: id = "wifi.raw.metrics"
/// mesh-api: component = "wifi"
/// mesh-api: method = "raw.metrics"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 6
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawMetricsRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
}

/// Return bounded raw action receive and dispatch counters
/// mesh-api: summary = "Return bounded raw action receive and dispatch counters"
/// mesh-api: id = "wifi.raw.metrics"
/// mesh-api: component = "wifi"
/// mesh-api: method = "raw.metrics"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 6
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawMetricsResponse;

/// Stop the raw action listener
/// mesh-api: summary = "Stop the raw action listener"
/// mesh-api: id = "wifi.raw.stop"
/// mesh-api: component = "wifi"
/// mesh-api: method = "raw.stop"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 7
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawStopRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
}

/// Stop the raw action listener
/// mesh-api: summary = "Stop the raw action listener"
/// mesh-api: id = "wifi.raw.stop"
/// mesh-api: component = "wifi"
/// mesh-api: method = "raw.stop"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 7
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawStopResponse;

/// Start or renew a bounded raw action listener
/// mesh-api: summary = "Start or renew a bounded raw action listener"
/// mesh-api: id = "wifi.raw.listen"
/// mesh-api: component = "wifi"
/// mesh-api: method = "raw.listen"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 8
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawListenRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
    /// API field `channel`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel: Option<u8>,
    /// API field `listen_sec`.
    /// mesh-api-field: index = 3
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub listen_sec: Option<u64>,
    /// API field `rx_variant`.
    /// mesh-api-field: index = 4
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rx_variant: Option<String>,
}

/// Start or renew a bounded raw action listener
/// mesh-api: summary = "Start or renew a bounded raw action listener"
/// mesh-api: id = "wifi.raw.listen"
/// mesh-api: component = "wifi"
/// mesh-api: method = "raw.listen"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 8
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawListenResponse;

/// Run one raw action liveness check
/// mesh-api: summary = "Run one raw action liveness check"
/// mesh-api: id = "wifi.raw.check"
/// mesh-api: component = "wifi"
/// mesh-api: method = "raw.check"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 9
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawCheckRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
    /// API field `channel`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel: Option<u8>,
    /// API field `destination`.
    /// mesh-api-field: index = 3
    /// mesh-api-field: required = true
    pub destination: String,
    /// API field `nonce`.
    /// mesh-api-field: index = 4
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nonce: Option<u64>,
    /// API field `timeout_ms`.
    /// mesh-api-field: index = 5
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout_ms: Option<u64>,
    /// API field `tx_rate_mbps`.
    /// mesh-api-field: index = 6
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tx_rate_mbps: Option<u8>,
    /// API field `tx_variant`.
    /// mesh-api-field: index = 7
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tx_variant: Option<String>,
    /// API field `rx_variant`.
    /// mesh-api-field: index = 8
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rx_variant: Option<String>,
    /// API field `expected_peer`.
    /// mesh-api-field: index = 9
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expected_peer: Option<String>,
}

/// Run one raw action liveness check
/// mesh-api: summary = "Run one raw action liveness check"
/// mesh-api: id = "wifi.raw.check"
/// mesh-api: component = "wifi"
/// mesh-api: method = "raw.check"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 9
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawCheckResponse;

/// Run raw action QUIC-lite IPERF
/// mesh-api: summary = "Run raw action QUIC-lite IPERF"
/// mesh-api: id = "wifi.raw.iperf"
/// mesh-api: component = "wifi"
/// mesh-api: method = "raw.iperf"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 10
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawIperfRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
    /// API field `channel`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel: Option<u8>,
    /// API field `destination`.
    /// mesh-api-field: index = 3
    /// mesh-api-field: required = true
    pub destination: String,
    /// API field `bytes`.
    /// mesh-api-field: index = 4
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bytes: Option<u64>,
    /// API field `packet_size`.
    /// mesh-api-field: index = 5
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub packet_size: Option<u16>,
    /// API field `timeout_ms`.
    /// mesh-api-field: index = 6
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeout_ms: Option<u64>,
    /// API field `tx_rate_mbps`.
    /// mesh-api-field: index = 7
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tx_rate_mbps: Option<u8>,
    /// API field `tx_variant`.
    /// mesh-api-field: index = 8
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tx_variant: Option<String>,
    /// API field `rx_variant`.
    /// mesh-api-field: index = 9
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rx_variant: Option<String>,
    /// API field `expected_peer`.
    /// mesh-api-field: index = 10
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expected_peer: Option<String>,
}

/// Run raw action QUIC-lite IPERF
/// mesh-api: summary = "Run raw action QUIC-lite IPERF"
/// mesh-api: id = "wifi.raw.iperf"
/// mesh-api: component = "wifi"
/// mesh-api: method = "raw.iperf"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 10
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawIperfResponse;

/// Send one raw Wi-Fi validation frame
/// mesh-api: summary = "Send one raw Wi-Fi validation frame"
/// mesh-api: id = "wifi.raw.send"
/// mesh-api: component = "wifi"
/// mesh-api: method = "raw.send"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 11
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawSendRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
    /// API field `channel`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel: Option<u8>,
    /// API field `tx_variant`.
    /// mesh-api-field: index = 3
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tx_variant: Option<String>,
    /// API field `tx_rate_mbps`.
    /// mesh-api-field: index = 4
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tx_rate_mbps: Option<u8>,
    /// API field `frame_hex`.
    /// mesh-api-field: index = 5
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub frame_hex: Option<String>,
}

/// Send one raw Wi-Fi validation frame
/// mesh-api: summary = "Send one raw Wi-Fi validation frame"
/// mesh-api: id = "wifi.raw.send"
/// mesh-api: component = "wifi"
/// mesh-api: method = "raw.send"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 11
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawSendResponse;

/// Send a bounded NAN discovery probe
/// mesh-api: summary = "Send a bounded NAN discovery probe"
/// mesh-api: id = "wifi.rawnan.ping"
/// mesh-api: component = "wifi"
/// mesh-api: method = "rawnan.ping"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 12
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawnanPingRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
    /// API field `channel`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel: Option<u8>,
    /// API field `destination`.
    /// mesh-api-field: index = 3
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub destination: Option<String>,
    /// API field `bssid`.
    /// mesh-api-field: index = 4
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bssid: Option<String>,
    /// API field `payload`.
    /// mesh-api-field: index = 5
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payload: Option<String>,
    /// API field `wait_ms`.
    /// mesh-api-field: index = 6
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub wait_ms: Option<u64>,
}

/// Send a bounded NAN discovery probe
/// mesh-api: summary = "Send a bounded NAN discovery probe"
/// mesh-api: id = "wifi.rawnan.ping"
/// mesh-api: component = "wifi"
/// mesh-api: method = "rawnan.ping"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 12
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawnanPingResponse;

/// Start or renew a bounded raw-NAN listener
/// mesh-api: summary = "Start or renew a bounded raw-NAN listener"
/// mesh-api: id = "wifi.rawnan.listen"
/// mesh-api: component = "wifi"
/// mesh-api: method = "rawnan.listen"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 14
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawnanListenRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
    /// API field `channel`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel: Option<u8>,
    /// API field `listen_sec`.
    /// mesh-api-field: index = 3
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub listen_sec: Option<u64>,
}

/// Start or renew a bounded raw-NAN listener
/// mesh-api: summary = "Start or renew a bounded raw-NAN listener"
/// mesh-api: id = "wifi.rawnan.listen"
/// mesh-api: component = "wifi"
/// mesh-api: method = "rawnan.listen"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 14
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiRawnanListenResponse;

