// Generated by mesh-api-gen from API.md; do not edit.

use serde::{Deserialize, Serialize};

/// Replace a node's volatile physical transport profile; NAN DW8 with NOW off is sleepy, while DW1 with NOW on is awake
/// mesh-api: summary = "Replace a node's volatile physical transport profile; NAN DW8 with NOW off is sleepy, while DW1 with NOW on is awake"
/// mesh-api: id = "transport.set"
/// mesh-api: component = "transport"
/// mesh-api: method = "set"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 1
/// mesh-api: method-index = 4
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TransportSetRequest {
    /// API field `kind`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = true
    pub kind: u8,
    /// API field `ssid`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ssid: Option<String>,
    /// API field `bssid`.
    /// mesh-api-field: index = 3
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bssid: Option<String>,
    /// API field `channel`.
    /// mesh-api-field: index = 4
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel: Option<u8>,
    /// API field `nan_dw_interval`.
    /// mesh-api-field: index = 14
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nan_dw_interval: Option<u8>,
    /// API field `now`.
    /// mesh-api-field: index = 15
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub now: Option<u8>,
    /// API field `ap`.
    /// mesh-api-field: index = 16
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ap: Option<u8>,
    /// API field `passphrase`.
    /// mesh-api-field: index = 17
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub passphrase: Option<String>,
    /// API field `ndp`.
    /// mesh-api-field: index = 19
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ndp: Option<u8>,
    /// API field `open`.
    /// mesh-api-field: index = 24
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub open: Option<bool>,
}

/// Replace a node's volatile physical transport profile; NAN DW8 with NOW off is sleepy, while DW1 with NOW on is awake
/// mesh-api: summary = "Replace a node's volatile physical transport profile; NAN DW8 with NOW off is sleepy, while DW1 with NOW on is awake"
/// mesh-api: id = "transport.set"
/// mesh-api: component = "transport"
/// mesh-api: method = "set"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 1
/// mesh-api: method-index = 4
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TransportSetResponse;

/// Send a mesh payload over the selected radio
/// mesh-api: summary = "Send a mesh payload over the selected radio"
/// mesh-api: id = "lmesh.send"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "send"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 8
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshSendRequest {
    /// API field `radio`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub radio: Option<String>,
    /// API field `destination`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub destination: Option<String>,
    /// API field `payload`.
    /// mesh-api-field: index = 3
    /// mesh-api-field: required = true
    pub payload: String,
}

/// Send a mesh payload over the selected radio
/// mesh-api: summary = "Send a mesh payload over the selected radio"
/// mesh-api: id = "lmesh.send"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "send"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 8
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshSendResponse;

/// Return configured local radio adapters
/// mesh-api: summary = "Return configured local radio adapters"
/// mesh-api: id = "lmesh.radios.list"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "radios.list"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 9
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshRadiosListRequest;

/// Return configured local radio adapters
/// mesh-api: summary = "Return configured local radio adapters"
/// mesh-api: id = "lmesh.radios.list"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "radios.list"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 9
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshRadiosListResponse;

/// Return recent radio and backend message history
/// mesh-api: summary = "Return recent radio and backend message history"
/// mesh-api: id = "lmesh.messages.history"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "messages.history"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 10
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshMessagesHistoryRequest {
    /// API field `keys`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub keys: Option<String>,
    /// API field `limit`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<u64>,
}

/// Return recent radio and backend message history
/// mesh-api: summary = "Return recent radio and backend message history"
/// mesh-api: id = "lmesh.messages.history"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "messages.history"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 10
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshMessagesHistoryResponse;

/// Capture a bounded host management-frame sample
/// mesh-api: summary = "Capture a bounded host management-frame sample"
/// mesh-api: id = "wifi.mgmt.capture"
/// mesh-api: component = "wifi"
/// mesh-api: method = "mgmt.capture"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 13
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiMgmtCaptureRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
    /// API field `channel`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel: Option<u8>,
    /// API field `capture_ms`.
    /// mesh-api-field: index = 3
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub capture_ms: Option<u64>,
    /// API field `max_frames`.
    /// mesh-api-field: index = 4
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_frames: Option<u64>,
    /// API field `active`.
    /// mesh-api-field: index = 5
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
}

/// Capture a bounded host management-frame sample
/// mesh-api: summary = "Capture a bounded host management-frame sample"
/// mesh-api: id = "wifi.mgmt.capture"
/// mesh-api: component = "wifi"
/// mesh-api: method = "mgmt.capture"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 13
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiMgmtCaptureResponse;
