android_library(
    name = "lib-lm",
    srcs = glob(["src/main/java/**/*.java"]),
    custom_package = "com.github.costinm.dmesh.lm",
    manifest = "src/main/AndroidManifest.xml",
    visibility = ["//visibility:public"],
    deps = [
        "//external:support-annotations",
    ],
)
