// Generated by mesh-api-gen from API.md; do not edit.

use serde::{Deserialize, Serialize};

/// List currently discovered local mesh nodes
/// mesh-api: summary = "List currently discovered local mesh nodes"
/// mesh-api: id = "lmesh.nodes"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "nodes"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 1
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshNodesRequest;

/// List currently discovered local mesh nodes
/// mesh-api: summary = "List currently discovered local mesh nodes"
/// mesh-api: id = "lmesh.nodes"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "nodes"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 1
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshNodesResponse;

/// List observed bearer-neutral announces
/// mesh-api: summary = "List observed bearer-neutral announces"
/// mesh-api: id = "lmesh.announces"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "announces"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 11
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshAnnouncesRequest;

/// List observed bearer-neutral announces
/// mesh-api: summary = "List observed bearer-neutral announces"
/// mesh-api: id = "lmesh.announces"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "announces"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 11
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshAnnouncesResponse;

/// Return one discovered node by public key
/// mesh-api: summary = "Return one discovered node by public key"
/// mesh-api: id = "lmesh.get_node"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "get_node"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 2
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshGetNodeRequest {
    /// API field `public_key`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = true
    /// mesh-api-field: position = 1
    pub public_key: String,
}

/// Return one discovered node by public key
/// mesh-api: summary = "Return one discovered node by public key"
/// mesh-api: id = "lmesh.get_node"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "get_node"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 2
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshGetNodeResponse;

/// Send a multicast local mesh announcement
/// mesh-api: summary = "Send a multicast local mesh announcement"
/// mesh-api: id = "lmesh.announce"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "announce"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 3
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshAnnounceRequest {
    /// API field `metadata`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

/// Send a multicast local mesh announcement
/// mesh-api: summary = "Send a multicast local mesh announcement"
/// mesh-api: id = "lmesh.announce"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "announce"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 3
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshAnnounceResponse;

/// Return local discovery and radio status
/// mesh-api: summary = "Return local discovery and radio status"
/// mesh-api: id = "lmesh.status"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "status"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 4
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshStatusRequest;

/// Return local discovery and radio status
/// mesh-api: summary = "Return local discovery and radio status"
/// mesh-api: id = "lmesh.status"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "status"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 4
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshStatusResponse;

/// Return recently observed neighbors
/// mesh-api: summary = "Return recently observed neighbors"
/// mesh-api: id = "lmesh.neighbors"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "neighbors"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 5
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshNeighborsRequest {
    /// API field `seen_within_sec`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seen_within_sec: Option<u64>,
}

/// Return recently observed neighbors
/// mesh-api: summary = "Return recently observed neighbors"
/// mesh-api: id = "lmesh.neighbors"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "neighbors"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 5
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshNeighborsResponse;

/// Return local link observations and selected paths
/// mesh-api: summary = "Return local link observations and selected paths"
/// mesh-api: id = "lmesh.links.list"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "links.list"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 6
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshLinksListRequest {
    /// API field `seen_within_sec`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seen_within_sec: Option<u64>,
}

/// Return local link observations and selected paths
/// mesh-api: summary = "Return local link observations and selected paths"
/// mesh-api: id = "lmesh.links.list"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "links.list"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 6
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshLinksListResponse;

/// Discover peers over one radio or all radios
/// mesh-api: summary = "Discover peers over one radio or all radios"
/// mesh-api: id = "lmesh.ping"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "ping"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 7
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshPingRequest {
    /// API field `radio`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub radio: Option<String>,
    /// API field `wait_ms`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub wait_ms: Option<u64>,
    /// API field `nonce`.
    /// mesh-api-field: index = 3
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nonce: Option<String>,
}

/// Discover peers over one radio or all radios
/// mesh-api: summary = "Discover peers over one radio or all radios"
/// mesh-api: id = "lmesh.ping"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "ping"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 7
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshPingResponse;

/// Send a mesh payload over the selected radio
/// mesh-api: summary = "Send a mesh payload over the selected radio"
/// mesh-api: id = "lmesh.send"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "send"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 8
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshSendRequest {
    /// API field `radio`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub radio: Option<String>,
    /// API field `destination`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub destination: Option<String>,
    /// API field `payload`.
    /// mesh-api-field: index = 3
    /// mesh-api-field: required = true
    pub payload: String,
}

/// Send a mesh payload over the selected radio
/// mesh-api: summary = "Send a mesh payload over the selected radio"
/// mesh-api: id = "lmesh.send"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "send"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 8
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshSendResponse;

/// Return configured local radio adapters
/// mesh-api: summary = "Return configured local radio adapters"
/// mesh-api: id = "lmesh.radios.list"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "radios.list"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 9
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshRadiosListRequest;

/// Return configured local radio adapters
/// mesh-api: summary = "Return configured local radio adapters"
/// mesh-api: id = "lmesh.radios.list"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "radios.list"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 9
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshRadiosListResponse;

/// Return recent radio and backend message history
/// mesh-api: summary = "Return recent radio and backend message history"
/// mesh-api: id = "lmesh.messages.history"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "messages.history"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 10
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshMessagesHistoryRequest {
    /// API field `keys`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub keys: Option<String>,
    /// API field `limit`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<u64>,
}

/// Return recent radio and backend message history
/// mesh-api: summary = "Return recent radio and backend message history"
/// mesh-api: id = "lmesh.messages.history"
/// mesh-api: component = "lmesh"
/// mesh-api: method = "messages.history"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 4
/// mesh-api: method-index = 10
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LmeshMessagesHistoryResponse;

/// Capture a bounded host management-frame sample
/// mesh-api: summary = "Capture a bounded host management-frame sample"
/// mesh-api: id = "wifi.mgmt.capture"
/// mesh-api: component = "wifi"
/// mesh-api: method = "mgmt.capture"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 13
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiMgmtCaptureRequest {
    /// API field `iface`.
    /// mesh-api-field: index = 1
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub iface: Option<String>,
    /// API field `channel`.
    /// mesh-api-field: index = 2
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub channel: Option<u8>,
    /// API field `capture_ms`.
    /// mesh-api-field: index = 3
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub capture_ms: Option<u64>,
    /// API field `max_frames`.
    /// mesh-api-field: index = 4
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_frames: Option<u64>,
    /// API field `active`.
    /// mesh-api-field: index = 5
    /// mesh-api-field: required = false
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
}

/// Capture a bounded host management-frame sample
/// mesh-api: summary = "Capture a bounded host management-frame sample"
/// mesh-api: id = "wifi.mgmt.capture"
/// mesh-api: component = "wifi"
/// mesh-api: method = "mgmt.capture"
/// mesh-api: visibility = "public"
/// mesh-api: component-index = 5
/// mesh-api: method-index = 13
/// mesh-api: shape = "response"
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct WifiMgmtCaptureResponse;
