// Generated by mesh-api-gen from API.md; do not edit.

use serde::{Deserialize, Serialize};

/// Query status for one service or all loaded services
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitStatusRequest {
    /// API field `name`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// Query status for one service or all loaded services
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitStatusResponse;

/// Start a configured service by name
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitStartRequest {
    /// API field `name`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// API field `args`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub args: Option<Vec<serde_json::Value>>,
    /// API field `env`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub env: Option<serde_json::Value>,
}

/// Start a configured service by name
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitStartResponse;

/// Gracefully terminate or signal a running service
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitStopRequest {
    /// API field `name`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// API field `signal`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub signal: Option<i32>,
}

/// Gracefully terminate or signal a running service
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitStopResponse;

/// Suspend a running service
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitFreezeRequest {
    /// API field `name`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// API field `reason`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

/// Suspend a running service
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitFreezeResponse;

/// Resume a frozen service
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitUnfreezeRequest {
    /// API field `name`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// Resume a frozen service
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitUnfreezeResponse;

/// Reload service configuration from disk
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitReloadRequest;

/// Reload service configuration from disk
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitReloadResponse;

/// Reconcile managed services after host resume or recovery
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitReconcileRequest;

/// Reconcile managed services after host resume or recovery
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitReconcileResponse {
    /// API field `checked`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub checked: Option<u64>,
    /// API field `reconciled`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reconciled: Option<u64>,
    /// API field `failed`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failed: Option<u64>,
}

/// Gracefully stop all services and shut down mesh-init
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitShutdownRequest;

/// Gracefully stop all services and shut down mesh-init
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitShutdownResponse;

/// List observed processes from the process observer
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitProcessesRequest;

/// List observed processes from the process observer
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitProcessesResponse;

/// Return detailed information for one process
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitProcessRequest {
    /// API field `pid`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pid: Option<u32>,
}

/// Return detailed information for one process
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitProcessResponse;

/// Return all observed cgroups
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitCgroupsRequest;

/// Return all observed cgroups
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitCgroupsResponse;

/// Return detailed information for one cgroup path
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitCgroupRequest {
    /// API field `path`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

/// Return detailed information for one cgroup path
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitCgroupResponse;

/// Return pressure watch state
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitPressureRequest;

/// Return pressure watch state
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitPressureResponse;

/// Set memory.high for a cgroup based on current memory usage
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitCgroupHighRequest {
    /// API field `path`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// API field `percentage`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub percentage: Option<f64>,
    /// API field `interval`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interval: Option<u64>,
}

/// Set memory.high for a cgroup based on current memory usage
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitCgroupHighResponse;

/// Move a process to a named cgroup
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitMoveProcessRequest {
    /// API field `pid`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pid: Option<u32>,
    /// API field `cgroup_name`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cgroup_name: Option<String>,
}

/// Move a process to a named cgroup
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitMoveProcessResponse;

/// Start a terminal with descriptors attached to its CBOR seqpacket request
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitStartTerminalRequest {
    /// API field `name`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// API field `home`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub home: Option<String>,
    /// API field `uid`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uid: Option<u32>,
    /// API field `gid`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gid: Option<u32>,
    /// API field `pty`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pty: Option<bool>,
    /// API field `env`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub env: Option<serde_json::Value>,
    /// API field `context`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context: Option<serde_json::Value>,
    /// API field `command`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    /// API field `fd_count`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fd_count: Option<u32>,
}

/// Start a terminal with descriptors attached to its CBOR seqpacket request
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitStartTerminalResponse;

/// Register a namespace descriptor attached to its CBOR seqpacket request
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitRegisterNamespaceRequest {
    /// API field `name`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// API field `kind`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    /// API field `target_pid`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target_pid: Option<u32>,
}

/// Register a namespace descriptor attached to its CBOR seqpacket request
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitRegisterNamespaceResponse;
