[package]
name = "dmesh-cli"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = "1.0"
dmesh-rawnan = { path = "../rawnan" }
dmesh-server = { path = "../dmesh-server", features = ["udp"] }
quic-lite = { path = "../quic-lite" }
libc = "0.2"
minicbor = "2.2"
sha2 = "0.11"
toml = "0.8"
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
uart-codec = { path = "../uart-codec" }
mesh = { git = "https://github.com/costinm/ssh-mesh", package = "mesh" }
serde_json = "1.0"
tokio = { version = "1", features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync"] }

[dev-dependencies]
lmesh = { path = "../lmesh" }
lmesh-wifi = { path = "../lmesh-wifi" }
tokio = { version = "1", features = ["time"] }
