[package]
name = "quic-lite"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
std = []

[dependencies]
hmac = { version = "0.13", default-features = false }
mesh-api = { git = "https://github.com/costinm/ssh-mesh", package = "mesh-api" }
sha2 = { version = "0.11", default-features = false }

[lib]
name = "quic_lite"
path = "src/lib.rs"
