// Generated by mesh-api-gen from API.md; do not edit.

use serde::{Deserialize, Serialize};

/// Receive a supervisor freeze or unfreeze notification
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshLifecycleRequest {
    /// API field `action`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    /// API field `cause`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cause: Option<String>,
    /// API field `observed`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub observed: Option<bool>,
}

/// Receive a supervisor freeze or unfreeze notification
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshLifecycleResponse {
    /// API field `subscribers`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subscribers: Option<u64>,
}

/// Return common service identity and descriptive metadata
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitializeRequest;

/// Return common service identity and descriptive metadata
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshInitializeResponse {
    /// API field `name`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// API field `version`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// API field `title`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// API field `instructions`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instructions: Option<String>,
}

/// Return the service's generated method catalog
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshToolsRequest;

/// Return the service's generated method catalog
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MeshToolsResponse {
    /// API field `tools`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<serde_json::Value>>,
}

/// Acknowledge trace-subscription capability on this control endpoint
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TraceSubscribeRequest;

/// Acknowledge trace-subscription capability on this control endpoint
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TraceSubscribeResponse {
    /// API field `subscribed`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subscribed: Option<bool>,
    /// API field `service`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service: Option<String>,
}

/// Set this process's reloadable tracing EnvFilter
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TraceSetLevelRequest {
    /// API field `level`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub level: Option<String>,
}

/// Set this process's reloadable tracing EnvFilter
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TraceSetLevelResponse {
    /// API field `level`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub level: Option<String>,
    /// API field `message`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

/// Return this process's current configured tracing EnvFilter
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TraceGetLevelRequest;

/// Return this process's current configured tracing EnvFilter
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TraceGetLevelResponse {
    /// API field `level`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub level: Option<String>,
    /// API field `message`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}
