// Generated by mesh-api-gen; do not edit.

pub const COMPONENT_MESH: u32 = 2000;
pub const METHOD_MESH_LIFECYCLE: u32 = 3;
pub const FIELD_MESH_LIFECYCLE_ACTION: u32 = 1;
pub const FIELD_MESH_LIFECYCLE_CAUSE: u32 = 2;
pub const FIELD_MESH_LIFECYCLE_OBSERVED: u32 = 3;
pub const METHOD_MESH_INITIALIZE: u32 = 1;
pub const METHOD_MESH_TOOLS: u32 = 2;
pub const COMPONENT_TRACE: u32 = 2001;
pub const METHOD_TRACE_SUBSCRIBE: u32 = 1;
pub const METHOD_TRACE_SET_LEVEL: u32 = 2;
pub const FIELD_TRACE_SET_LEVEL_LEVEL: u32 = 1;
pub const METHOD_TRACE_GET_LEVEL: u32 = 3;
